django_proyect/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from users import views as user_views
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/', user_views.register, name ='register'),
    path('profile/', user_views.profile, name ='profile'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name ='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name ='logout'),
    path('webShop/', include('webshop.urls')),
 

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

webshop/urls.py
from django.urls import include, path
from django.conf.urls import url
from . import views
from . import forms
from .views import (
    PostCreateView,
    PostUpdateView,
    PostDeleteView,
    ItemDetailView,
    HomeView,
    HomeViewShortedByHighPrice,
    HomeViewShortedByLowPrice,
    HomeViewShortedByAName,
    HomeViewShortedByZName,
    add_to_cart,
    remove_from_cart,
    OrderSummaryView,
    CheckoutView,
    remove_single_item_from_cart,
)

#app_name= 'webshop'

urlpatterns = [
    path('item_list/', HomeView.as_view(), name='item_list'),
    path('HomeViewShortedByHighPrice/', HomeViewShortedByHighPrice.as_view(), name='HomeViewShortedByHighPrice'),
    path('HomeViewShortedByLowPrice/', HomeViewShortedByLowPrice.as_view(), name='HomeViewShortedByLowPrice'),
    path('HomeViewShortedByAName/', HomeViewShortedByAName.as_view(), name='HomeViewShortedByAName'),
    path('HomeViewShortedByZName/', HomeViewShortedByZName.as_view(), name='HomeViewShortedByZName'),
    path('add_to_cart/<int:pk>/',add_to_cart, name='add_to_cart'),
    path('remove_from_cart/<int:pk>/',remove_from_cart, name='remove_from_cart'),
    path('remove_single_item_from_cart/<int:pk>/',remove_single_item_from_cart, name='remove_single_item_from_cart'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/',OrderSummaryView.as_view(), name='order-summary'),
    path('item/<int:pk>/', ItemDetailView.as_view(), name='item-detail'),
    path('product/<int:pk>/', ItemDetailView.as_view(), name='product'),
    path('item/new/', PostCreateView.as_view(), name='item-create'),
    path('item/<int:pk>/update/', PostUpdateView.as_view(), name='item-update'),
    path('item/<int:pk>/delete/', PostDeleteView.as_view(), name='item-delete'),
    path('about/', views.about, name='shop-about'),

]

webshop/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.conf import settings
from django.urls import reverse
from datetime import datetime
from PIL import Image
from django_countries.fields import CountryField



CATEGORY_CHOISES = (
    ('A', 'All'),
    ('P', 'Phone'),
    ('C', 'Car'),
    ('L', 'Lamp')
)

LABEL_CHOISES = (
    ('p', 'primary'),
    ('s', 'secondary'),
    ('d', 'danger'),
    ('D', 'default'),
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

class Item(models.Model):

    name = models.CharField(max_length=50)
    description = models.TextField(max_length=100)
    photo = models.ImageField(upload_to='item_pics', default='default.jpg', null=True)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOISES, max_length=2)
    label = models.CharField(choices=LABEL_CHOISES, max_length=1)
    created_at = models.DateTimeField(default=datetime.now)
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE, blank=True, default ='juan')
    slug = models.SlugField()
    
    def __str__(self):
    	return self.name

    
    def save(self):
        super().save()

        img = Image.open(self.photo.path)

        if img.height > 300 or img.width > 300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.photo.path)

    def get_absolute_url(self):
        #return reverse('item-detail', kwargs={'pk': self.pk})
        return reverse('product', kwargs={'pk': self.pk})

    def get_add_to_cart_url(self):
         return reverse('add_to_cart', kwargs={'pk': self.pk})

    def get_remove_from_cart_url(self):
         return reverse('remove_from_cart', kwargs={'pk': self.pk})



class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.name}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        if self.item.discount_price == 'null':
            return 0
        else:
            return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()


class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total

    def get_total_saved(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_amount_saved()
        return total

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural = 'Addresses'


class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.user.username


class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code


class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField()

    def __str__(self):
        return f"{self.pk}"

webshop/views.py
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.core.exceptions import ObjectDoesNotExist
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib import messages
from django.shortcuts import redirect
from django.utils import timezone
from django.views.generic import ListView, DetailView, CreateView, UpdateView, DeleteView
from .models import Item, Order, OrderItem, Address
from .forms import CheckoutForm, CouponForm


def category_choises(request):
	my_model = Model.objects.values('category_choises').distinct()
	return render(request, 'webshop/item_list.html')


def home(request):
	context = {
		'items': Item.objects.all()
	}
	return render(request, 'webshop/home.html', context)


class CheckoutView(DetailView):
    def get(self, *args, **kwargs):
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            form = CheckoutForm()
            context = {
                'form': form,
                'couponform': CouponForm(),
                'order': order,
                'DISPLAY_COUPON_FORM': True
            }

            shipping_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='S',
                default=True
            )
            if shipping_address_qs.exists():
                context.update(
                    {'default_shipping_address': shipping_address_qs[0]})

            billing_address_qs = Address.objects.filter(
                user=self.request.user,
                address_type='B',
                default=True
            )
            if billing_address_qs.exists():
                context.update(
                    {'default_billing_address': billing_address_qs[0]})
            return render(self.request, "webshop/checkout.html", context)
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("item_list")

    def post(self, *args, **kwargs):
        form = CheckoutForm(self.request.POST or None)
        try:
            order = Order.objects.get(user=self.request.user, ordered=False)
            if form.is_valid():

                use_default_shipping = form.cleaned_data.get(
                    'use_default_shipping')
                if use_default_shipping:
                    print("Using the defualt shipping address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='S',
                        default=True
                    )
                    if address_qs.exists():
                        shipping_address = address_qs[0]
                        order.shipping_address = shipping_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default shipping address available")
                        return redirect('checkout')
                else:
                    print("User is entering a new shipping address")
                    shipping_address1 = form.cleaned_data.get(
                        'shipping_address')
                    shipping_address2 = form.cleaned_data.get(
                        'shipping_address2')
                    shipping_country = form.cleaned_data.get(
                        'shipping_country')
                    shipping_zip = form.cleaned_data.get('shipping_zip')

                    if is_valid_form([shipping_address1, shipping_country, shipping_zip]):
                        shipping_address = Address(
                            user=self.request.user,
                            street_address=shipping_address1,
                            apartment_address=shipping_address2,
                            country=shipping_country,
                            zip=shipping_zip,
                            address_type='S'
                        )
                        shipping_address.save()

                        order.shipping_address = shipping_address
                        order.save()

                        set_default_shipping = form.cleaned_data.get(
                            'set_default_shipping')
                        if set_default_shipping:
                            shipping_address.default = True
                            shipping_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required shipping address fields")

                use_default_billing = form.cleaned_data.get(
                    'use_default_billing')
                same_billing_address = form.cleaned_data.get(
                    'same_billing_address')

                if same_billing_address:
                    billing_address = shipping_address
                    billing_address.pk = None
                    billing_address.save()
                    billing_address.address_type = 'B'
                    billing_address.save()
                    order.billing_address = billing_address
                    order.save()

                elif use_default_billing:
                    print("Using the defualt billing address")
                    address_qs = Address.objects.filter(
                        user=self.request.user,
                        address_type='B',
                        default=True
                    )
                    if address_qs.exists():
                        billing_address = address_qs[0]
                        order.billing_address = billing_address
                        order.save()
                    else:
                        messages.info(
                            self.request, "No default billing address available")
                        return redirect('checkout')
                else:
                    print("User is entering a new billing address")
                    billing_address1 = form.cleaned_data.get(
                        'billing_address')
                    billing_address2 = form.cleaned_data.get(
                        'billing_address2')
                    billing_country = form.cleaned_data.get(
                        'billing_country')
                    billing_zip = form.cleaned_data.get('billing_zip')

                    if is_valid_form([billing_address1, billing_country, billing_zip]):
                        billing_address = Address(
                            user=self.request.user,
                            street_address=billing_address1,
                            apartment_address=billing_address2,
                            country=billing_country,
                            zip=billing_zip,
                            address_type='B'
                        )
                        billing_address.save()

                        order.billing_address = billing_address
                        order.save()

                        set_default_billing = form.cleaned_data.get(
                            'set_default_billing')
                        if set_default_billing:
                            billing_address.default = True
                            billing_address.save()

                    else:
                        messages.info(
                            self.request, "Please fill in the required billing address fields")

                payment_option = form.cleaned_data.get('payment_option')

                if payment_option == 'S':
                    return redirect('payment', payment_option='stripe')
                elif payment_option == 'P':
                    return redirect('payment', payment_option='paypal')
                else:
                    messages.warning(
                        self.request, "Invalid payment option selected")
                    return redirect('checkout')
        except ObjectDoesNotExist:
            messages.warning(self.request, "You do not have an active order")
            return redirect("item_list")

class PostCreateView(LoginRequiredMixin, CreateView):
	model = Item
	fields = ['name','price','category','description','photo','author']
	
	def form_valid(self, form):
		user = self.request.user
		return super().form_valid(form)
	

	def img_url(self):
		if self.photo and hasattr(self.photo,'url'):
			return self.photo.url
		

	
class PostUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
	model = Item
	fields = ['name','price','category','description','photo','author']
	

	#def form_valid(self, form):
	#	form.instance.photo.url = './default.jpg'
	#	return super().form_valid(form)

	def form_valid(self, form):
		user = self.request.user
		return super().form_valid(form)

	def test_func(self):
		item = self.get_object()
		if self.request.user == item.author:
			return True
		return False


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
	model = Item
	success_url = '/webshop/'
	def test_func(self):
		item = self.get_object()
		if self.request.user == item.author:
			return True
		return False


def about(request):
	return render(request, 'webshop/about.html', {'title': 'about'})


def HomeViewShortedByHighPrice(request):
	
	orderBy = 'HighPrice'
	ordering = ['-price']
	paginate_by = 10
	items_list = Item.objects.all()
	
	return render(request, 'webshop/item_list.html', {'orderBy': orderBy, 'items': items_list})


class HomeView(ListView):
	model = Item
	template_name = 'webshop/home-page.html' #app>/<model>_<viewtype>.html
	orderBy = 'Default'
	context_object_name = 'items'
	paginate_by = 10
	

class HomeViewShortedByHighPrice(ListView):
	model = Item
	template_name = 'webshop/home-page.html' #app>/<model>_<viewtype>.html

webshop/templates/webshop/about.html
{% extends "webshop/base.html" %}

{% block content %}
	<h1>about this shop </h1>
	
{% endblock content %}

webshop/templates/webshop/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %}
  {% endblock %}
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css">
  <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/mdb.min.css' %}" rel="stylesheet">
  <link href="{% static 'css/style.min.css' %}" rel="stylesheet">
  <style type="text/css">
    html,
    body,
    header,
    .carousel {
      height: 60vh;
    }

    @media (max-width: 740px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

    @media (min-width: 800px) and (max-width: 850px) {

      html,
      body,
      header,
      .carousel {
        height: 100vh;
      }
    }

  </style>
</head>


{% include "webshop/navbar.html" %}


<body>

    <div class="mt-5 pt-4">
    {% if messages %}
        {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        {% endfor %}
    {% endif %}
    </div>

    {% block content %}
    {% endblock content %}

    {% block extra_body %}
    {% endblock %}

    {% include "webshop/footer.html" %}
    {% include "webshop/scripts.html" %}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
</body>
</html>

webshop/templates/webshop/footer.html
<footer class="page-footer text-center font-small mt-4 wow fadeIn">

    <hr class="my-4">

    <!-- Social icons -->
    <div class="pb-4">
      <a href="https://www.facebook.com/mdbootstrap" target="_blank">
        <i class="fab fa-facebook-f mr-3"></i>
      </a>

      <a href="https://twitter.com/MDBootstrap" target="_blank">
        <i class="fab fa-twitter mr-3"></i>
      </a>

      <a href="https://www.youtube.com/watch?v=7MUISDJ5ZZ4" target="_blank">
        <i class="fab fa-youtube mr-3"></i>
      </a>

      <a href="https://plus.google.com/u/0/b/107863090883699620484" target="_blank">
        <i class="fab fa-google-plus-g mr-3"></i>
      </a>

      <a href="https://dribbble.com/mdbootstrap" target="_blank">
        <i class="fab fa-dribbble mr-3"></i>
      </a>

      <a href="https://pinterest.com/mdbootstrap" target="_blank">
        <i class="fab fa-pinterest mr-3"></i>
      </a>

      <a href="https://github.com/mdbootstrap/bootstrap-material-design" target="_blank">
        <i class="fab fa-github mr-3"></i>
      </a>

      <a href="http://codepen.io/mdbootstrap/" target="_blank">
        <i class="fab fa-codepen mr-3"></i>
      </a>
    </div>
    <!-- Social icons -->

    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="https://mdbootstrap.com/education/bootstrap/" target="_blank"> MDBootstrap.com </a>
    </div>
    <!--/.Copyright-->

  </footer>

webshop/templates/webshop/home-page.html
{% extends "webshop/base2.html" %}

{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Short by:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          <ul class="navbar-nav mr-auto">
            {% if item.orderBy == 'Default' %}
              <li class="nav-item active">
            {% else %}
              <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'item_list' %}">All</a>
              </li>
            {% if item.orderBy == 'AName' %}
              <li class="nav-item active">
            {% else %}
              <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'HomeViewShortedByAName' %}">Name(A-Z)</a>
              </li>
            {% if item.orderBy == 'ZName' %}
              <li class="nav-item active">
            {% else %}
              <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'HomeViewShortedByZName' %}">Name(Z-A)</a>
              </li>
            {% if item.orderBy == 'LowPrice' %}
              <li class="nav-item active">
            {% else %}
              <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'HomeViewShortedByLowPrice' %}">Price(Lower first)</a>
              </li>
            {% if item.orderBy == 'HighPrice' %}
              <li class="nav-item active">
            {% else %}
              <li class="nav-item">
            {% endif %}
                <a class="nav-link" href="{% url 'HomeViewShortedByHighPrice' %}">Price(Higher first)</a>
              </li>
          </ul>
          <!-- Links -->

                    <!-- Links 
          <ul class="navbar-nav mr-auto">
            {% for item in object_list %}
              <li class="nav-item active">
                <a class="nav-link" href="#">{{item.category}}
                <span class="sr-only">(current)</span>
                </a>
                </li>
            {% endfor %}
          </ul>
            Links -->

          <form class="form-inline">
            <div class="md-form my-0">
              <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->

      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <!--Grid row-->
        <div class="row wow fadeIn">

          {% for item in object_list %}
          <!--Grid column-->
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <img src="{{item.photo.url}}" class="card-img-top" style="width:  220px; height: 220px; max-width: 220px; max-height: 220px, display: block; margin-left: auto; margin-right: auto" alt="">
                <a href="{{item.get_absolute_url}}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
              
                <h5>
                  <strong>
                    <a href="" class="dark-grey-text">{{ item.name }}
                      {% if item.get_label_display == 'primary' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      {% elif item.get_label_display == 'secondary' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">DEAL</span>
                      {% elif item.get_label_display == 'danger' %}
                        <span class="badge badge-pill {{ item.get_label_display }}-color">OFER</span>
                      {% else %}
                      {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  
                  <strong>
                    {% if item.discount_price %}
                      {{ item.discount_price }}€
                    {% else %}
                      {{ item.price }}€
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          <!--Grid column-->

          {% endfor %}

        </div>
        <!--Grid row-->



      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}

    {% if page_obj.has_previous %}
      <a class = "btn btn-outline-info mb-4" href="?page=1">First</a>
      <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.previous_page_number}}">Previous</a>
    {% endif %}

    {% for num in page_obj.paginator.page_range %}
      {% if page_obj.number == num %}
        <a class = "btn btn-info mb-4" href="?page={{num}}">{{num}}</a>
      {% elif num > page_obj.number|add:'-3' and num < page_obj.number|add:'3' %}
        <a class = "btn btn-outline-info- mb-4" href="?page={{num}}">{{num}}</a>
      {% endif %}
    {% endfor %}

    {% if page_obj.has_next %}
      <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.next_page_number}}">Next</a>
      <a class = "btn btn-outline-info mb-4" href="?page={{page_obj.paginator.num_pages}}">Last</a>
    {% endif %}

  {% endif %}

      <!--Pagination-->

    </div>
  </main>
  <!--Main layout-->

  {% endblock content %}

webshop/templates/webshop/item_confirm_delete.html
{% extends "webshop/base.html" %}


{% block content %}
	
	<h1>Register now!</h1>
	<div class="content-section">
		<form method="POST">
			{% csrf_token %}
			<fielset class="form-group">
				<legend class="border-bottom mb-4"> Delete Item</legend>
					<h2>Are you sure you want to delete this item? "{{object.name}}"</h2>
			</fielset>

			<div class="form-group">
				<button class="btn btn-outline-danger" type="submit">yes,  delete</button>
				<a class="btn btn-outline-secondary" href="{% url 'item-detail' object.id %}">Cancel</a>
			</div>
		</form>
	</div>
	
	
{% endblock content %}

webshop/templates/webshop/item_form.html
{% extends "webshop/base2.html" %}
{% load crispy_forms_tags %}

{% block content %}
	
	<div class="container col-2">
		<div class="content-section">
			<form method="POST" enctype = "multipart/form-data">
				{% csrf_token %}
				<fielset class="form-group">
					<legend class="border-bottom mb-4"> New Item</legend>
					{{form|crispy}}
				</fielset>

				<div class="form-group">
					<button class="btn btn-outline-info" type="submit"> Add</button>
				</div>
			</form>
		</div>
	</div>
	
	
{% endblock content %}

webshop/templates/webshop/product.html
{% extends "webshop/base2.html" %}

{% block content %}

  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.photo.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <a href="">
                <span class="badge purple mr-1">{{ object.get_category_display }}</span>
              </a>
            </div>

            <p class="lead">
              {% if object.discount_price %}
              <span class="mr-1">
                <del>${{ object.price }}</del>
              </span>
              <span>${{ object.discount_price }}</span>
              {% else %}
              <span>${{ object.price }}</span>
              {% endif %}
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{ object.description }}</p>

            {% comment %} <form class="d-flex justify-content-left">
              <!-- Default input -->
              <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px">
              <button class="btn btn-primary btn-md my-0 p" type="submit">
                Add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
              </button>

            </form> {% endcomment %}
            <a href="{{ object.get_add_to_cart_url }}" class="btn btn-primary btn-md my-0 p">
              Add to cart
              <i class="fas fa-shopping-cart ml-1"></i>
            </a>
            <a href="{{ object.get_remove_from_cart_url }}" class="btn btn-danger btn-md my-0 p">
              Remove from cart
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>

{% endblock content %}